/*
 * LCD_PRIVATE.h
 *
 *  Created on: Aug 20, 2026
 *      Author: zom22
 */

#include "../../LIB/BIT_MATH.h"

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

//#define LCD_CMD_DISPLAY_CLEAR  				CONC_BIT(0,0,0,0,0,0,0,1)
//#define LCD_CMD_RETURN_HOME    				CONC_BIT(0,0,0,0,0,0,1,0)
//#define LCD_CMD_ENTRY_MODE_SET 	    		CONC_BIT(0,0,0,0,0,1,LCD_ID,LCD_S)
//#define LCD_CMD_DISPLAY_ON_OFF_CONTROL  	CONC_BIT(0,0,0,0,1,LCD_D,LCD_C,LCD_B)
//#define LCD_CMD_CURSOR_DISPLAY_SHIFT        CONC_BIT(0,0,0,1,LCD_SC,LCD_RL,0,0)
//#define LCD_CMD_FUNCTION_SET		        CONC_BIT(0,0,1,LCD_DL,LCD_N,LCD_F,0,0)
//
//#define LCD_ROW1_ADDRESS 					127
//#define LCD_ROW2_ADDRESS 					191

#define FUNCTION_SET 	    	CONC_BIT(0,0,1,LCD_DL,LCD_NO_OF_LINES,LCD_CHAR_FONT,0,0)
#define DISPLAY_ON_OFF_CONTROL 	CONC_BIT(0,0,0,0,1,DISPLAY_ON,CURSOR_DISPLAY,CURSOR_BLINK)
#define DISPLAY_CLEAR    		0x01
#define ENTRY_MODE_SET 			CONC_BIT(0,0,0,0,0,1,LCD_DATA_DIRECTION,LCD_SHIFT)

#define LCD_ROW1_ADDRESS 127
#define LCD_ROW2_ADDRESS 191


#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
